name: audit-check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions: {}
jobs:
  audit-check:
    permissions:
      contents: read
    uses: muleyuck/github-actions/.github/workflows/audit-rust.yml@v1
